TRI = $(HOME)/tri
ARCH = unix
POLL = poll
CFLAGS += "-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE"

include $(TRI)/config/Common

FILES = rgb palette msg new getopt
NAME = rgb

include $(TRI)/config/Rules

